### ISSUE TITLE
ffmpeg Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by faridcher** [C0D3D3V/bbb-dl#21]
I get this error while downloading this class session (https://class8.ui.ac.ir/playback/presentation/2.3/5bd7dde5d9d3789198317dbf09188628216535f1-1665232355123)

```sh
...
[BBB] Trimming slide (frame 189 / 193) at time stamp 01:04:44 (Duration: 00:00)

WARNING: [BBB] Something went wrong, please try again!
Error: Output file #0 does not contain any stream
```

**Comment by C0D3D3V** [comment]
I guess a duration of 00:00 is problematic xD I thought I had taken that into account when I programmed it. But apparently not, I will have a look at it the days.

**Comment by C0D3D3V** [comment]
So I finally had time to test your session. For me it worked without problems. Nonetheless I noticed your server is very unstable and a few files were broken on the first download attempt. Thats why I added a more secure way to download the files (you can anyway check if the downloaded images and videos are all fine, after bbb-dl has downloaded them, if they are not fine, just delete the broken file and rerun bbb-dl, it will redownload missing files)

Please update by running `pip install --user -U bbb-dl`

If you want I can upload the video for you that I generated from your session, but I guess since it is so old you do not need it anymore.
