### ISSUE TITLE
pause feature :)

### ISSUE THREAD

**Issue by Qbreak** [C0D3D3V/bbb-dl#36]
Is it possible to add a pause feature if it won't take your time?  pleaseeeenn

**Comment by C0D3D3V** [comment]
I do not think this is a good idea, since this is the job of the Operation System / Shell.

On windows you can press [Pause Break] to pause a program in PowerShell and resume with [Enter].

On MacOs, Linux you can press [Ctr+Z] to suspend a program and resume by typing `fg`.

**Comment by C0D3D3V** [comment]
This should at least work in all cases, except when capturing frames with chrome, because playwright is starting a node.js server, which communication is broken if the client is suspended. I have nearly no control over this communication, the only thing I could add is a retry loop, in case of a failure.

**Comment by Qbreak** [comment]
Worked :D

> I do not think this is a good idea, since this is the job of the Operation System / Shell.
> 
> On windows you can press [Pause Break] to pause a program in PowerShell and resume with [Enter].
> 
> On MacOs, Linux you can press [Ctr+Z] to suspend a program and resume by typing `fg`.
