### ISSUE TITLE
Keeping a log file

### ISSUE THREAD

**Issue by farid220** [C0D3D3V/bbb-dl#65]
First of all thanks for your incredible tool for downloading bbb sessions I personally prefer to have videos offline.
I was downloading 9  bbb sessions simultaneously separately in 9 different Terminals (I know, I should have used the batch downloading option). I ran them  and went to sleep and it seems when I was sleeping there was a power outage.

So now I don't know which one of them is finished successfully and which ones are not. A log file to keep track of them would be appreciated.

**Comment by C0D3D3V** [comment]
Thank you very much :)

First of all, I would recommend you using bbb-dl-batch. Because it already logs failures and successfully downlaoded sessions. And bbb-dl itself is already highly parallelized, so running multiple bbb-dl at the same time will not improve speed much, or could even slow down the process.

Yes, we could add a log option, and finally move to python standard logging. (I do not know why I did not do it already).

But for now you could use piping, that your terminal already provids.

like running bbd-dl like:
`bbb-dl options > path_to_log_file.txt`

or if you are on linux you could log to both, the terminal and a log file like this:

`bbb-dl options | tee path_to_log_file.txt`

you can use this till we add a logging option

**Comment by farid220** [comment]
Thanks so much for the prompt reply!

Yes that is a really good suggestion I will do it the way you recommended it
